In [40]:
import numpy as np

In [39]:
%run ../src/pathfinding.ipynb
%run ../src/capture-screen-2.ipynb

In [33]:
cells = [
    [0,0,0,0,0,0,0,0],
    [0,2,2,0,0,0,0,0],
    [0,2,0,0,0,0,0,0],
    [0,2,0,0,0,0,0,0],
    [0,2,3,-1,-1,-1,0,0],
    [0,0,0,0,0,-1,0,0],
    [0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0]
]

cells = np.array(cells)

In [34]:
path = [Position(4,2), Position(4,3), Position(4,4), Position(4,5), Position(5,5), Position(6,5)]
apple_pos = Position(6,5)
head_pos = Position(4,2)
snake_pos = [Position(4,2), Position(4,1), Position(3,1), Position(2,1), Position(1,1), Position(1,2)]

In [35]:
new_cells, new_snake_pos, new_head_pos = replace_snake_body(cells, path, snake_pos)

In [36]:
# new_cells, new_snake_pos, new_head_pos = augment_snake_body_2(cells, snake_pos, head_pos, apple_pos, Direction.BOTTOM, 3)

In [37]:
print(new_cells)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
