In [1]:
import numpy as np

In [15]:
%run Pathfinding.ipynb
%run Capture-screen.ipynb

In [4]:
cells = [
    [0,0,0,0,0,0,0,0],
    [0,2,2,0,0,0,0,0],
    [0,2,0,0,0,0,0,0],
    [0,2,0,0,0,0,0,0],
    [0,2,3,-1,-1,-1,0,0],
    [0,0,0,0,0,-1,0,0],
    [0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0]
]

cells = np.array(cells)

In [17]:
path = [Position(4,2), Position(4,3), Position(4,4), Position(4,5), Position(5,5), Position(6,5)]
apple_pos = Position(6,5)
head_pos = Position(4,2)
snake_pos = [Position(4,2), Position(4,1), Position(3,1), Position(2,1), Position(1,1), Position(1,2)]

In [20]:
# new_body_pos = []
# extended = False
# if(len(path[1:]) >= len(body_pos)+1):
#     length = len(body_pos) + 1
# else:
#     length = len(path[1:])
#     ext_length = len(body_pos) + 1 - len(path[1:])
#     extended = True
    
# for i in range(-1,-length-1,-1):
#     new_body_pos.append(path[i])
# if(extended):
#     for i in range(ext_length):
#         new_body_pos.append(body_pos[i])
        
# new_cells = np.zeros((8,8), dtype=np.int8)
# for pos in new_body_pos:
#     new_cells[pos.y, pos.x] = 2
# new_cells[apple_pos.y, apple_pos.x] = 3

In [21]:
new_cells, new_snake_pos, new_head_pos = replace_snake_body(path, snake_pos, apple_pos)

In [22]:
print(new_cells)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
