In [1]:
import cv2
import time
import asyncio
import concurrent.futures

import numpy as np

from mss import mss

In [82]:
def pathfinding(img):
#     (left, upper, right, lower) = (572, 271, 1330, 940)
#     img_crp = img[upper:lower, left:right]

    threshold = 0
    cells, head_pos = get_cells(img, Label, threshold)
    
    if(head_pos is None):
        return None
    
    cm_pos = center_of_mass(cells, nrows, ncols)
#     min_body_pos = find_min_max_body_pos(cells, nrows, ncols, True)
#     max_body_pos = find_min_max_body_pos(cells, nrows, ncols, False)

    new_cells = find_optimal_path(cells, head_pos, [cm_pos], [0])
    if(new_cells is None):
        return None

    print(new_cells)
    print("=============================")
    
    return new_cells

In [76]:
# detect game over
def game_over(img):
    (left, top, right, bottom) = (488, 466, 569, 547)
    img_crp = img[top:bottom, left:right]
    
    img_score_path = 'img_raw/gameover.png'
    img_score_full = cv2.imread(img_score_path)
    img_score = img_score_full[top:bottom, left:right]
    
    hist_crp = calc_hist(img_crp)
    hist_score = calc_hist(img_score)
    
    sum_diff = 0
    for chan in range(3):
        diff = cv2.compareHist(hist_crp[chan], hist_score[chan], cv2.HISTCMP_CORREL)
        sum_diff += diff
    
    avg_diff = sum_diff/3
    if(avg_diff>0.9):
        return True
    
    return False

In [78]:
%run Pathfinding.ipynb
%run astar.ipynb

In [70]:
def screenshot():
    start_time = time.time()
    with mss() as sct:        
        monitor_number = 1
        mon = sct.monitors[monitor_number]
        monitor = {'mon': monitor_number, 'width': 758, 'height': 669, 'left': mon["left"] + 572, 'top': mon["top"] + 271}
#         monitor = {'mon': monitor_number, 'width': 1920, 'height': 1080, 'left': 0, 'top': 0}

        sct_img = sct.grab(monitor)
        img = np.array(sct_img.pixels).astype(np.uint8)[::,::,::-1]
        
        end_time = time.time()
        duration = end_time - start_time
#         print(duration)
        
        return img

In [85]:
def main():    
    while(True):
        start_time = time.time()
        img_ret = screenshot()
        new_cells = pathfinding(img_ret)

        gameover = game_over(img_ret)
        if(gameover):
            print("game over")
            break
            
        duration = time.time() - start_time
        print(duration)

In [87]:
main()

0.5301039218902588
0.53446364402771
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  3 -1 -1 -1 -1 -1 -1 -1 -1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
0.5558018684387207
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  3  2  2  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  1 -1  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
0.5413286685943604
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  2  3 -1 -1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  2  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
0.5392496585845947
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 